import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Anotador de truco',
  description: 'Generated by Andres Medina',
}

// Sin chrome global a propósito: Login (sin ningún header) y Home (círculo
// flotante "Mi perfil") tienen su propio chrome — cada page.tsx decide el
// suyo. El resto de las pantallas comparten ese mismo círculo flotante vía
// el layout de (con-navbar)/.
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
