import './globals.css'
import { Baloo_2, Nunito } from 'next/font/google'

const display = Baloo_2({
  subsets: ['latin'],
  weight: ['600', '700', '800'],
  variable: '--font-display',
})
const sans = Nunito({
  subsets: ['latin'],
  weight: ['400', '600', '700', '800'],
  variable: '--font-sans',
})

export const metadata = {
  title: 'Anotador de truco',
  description: 'Generated by Andres Medina',
}

// Sin chrome global a propósito: Login (sin ningún header) y Home (círculo
// flotante "Mi perfil") tienen su propio chrome — cada page.tsx decide el
// suyo. El resto de las pantallas comparten ese mismo círculo flotante vía
// el layout de (con-navbar)/.
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={`${display.variable} ${sans.variable} bg-bg font-sans text-ink antialiased`}>
        {children}
      </body>
    </html>
  )
}
